import type { EmailBranding } from "./types"
import type { Order } from "@/lib/orders/types"
import { orderSummaryHtml, lowStockItemsHtml, type LowStockEmailItem } from "../templates"

/**
 * Pure, client-safe sample data for live previews in the admin builder. Mirrors
 * the real token set so previews look like a genuine send. NOT used at send time
 * — real sends fill tokens from the order/customer/campaign context.
 */
export function sampleVars(branding: EmailBranding): Record<string, string> {
  return {
    customer_name: "Ada Lovelace",
    brand_name: branding.brandName || "MOMO",
    order_number: "MOMO-1024",
    shop_url: "/products",
    offer_headline: "15% off",
    offer_label: "Welcome offer",
    offer_expiry: "Valid until 31 December 2026.",
  }
}

/** Sample order, shaped like a real `Order`, used to drive every dynamic preview block below. */
const SAMPLE_ORDER: Order = {
  id: "sample-order",
  number: "MOMO-1024",
  userId: "sample-user",
  email: "ada@example.com",
  createdAt: new Date().toISOString(),
  status: "processing",
  items: [
    { slug: "momo-reference-one", name: "MOMO Reference One", image: "/products/momo-beat.png", color: "Midnight", quantity: 1, unitAmount: 349, currency: "GBP" },
    { slug: "momo-buds-pro", name: "MOMO Buds Pro", image: "/products/momo-air.png", color: "Graphite", quantity: 1, unitAmount: 199, currency: "GBP" },
  ],
  subtotal: 548,
  shipping: 0,
  total: 548,
  currency: "GBP",
}

/**
 * Sample order-summary table so the orderSummary dynamic block renders in
 * previews. Generated by the same `orderSummaryHtml` function used at send
 * time (not a hand-maintained copy), so the builder preview can never drift
 * out of sync with what customers actually receive.
 */
export const SAMPLE_ORDER_SUMMARY = orderSummaryHtml(SAMPLE_ORDER)

const SAMPLE_LOW_STOCK_ITEMS_DATA: LowStockEmailItem[] = [
  { name: "MOMO Reference One", slug: "momo-reference-one", image: "/products/momo-beat.png", stock: 2, threshold: 5 },
  { name: "MOMO Buds Pro", slug: "momo-buds-pro", image: "/products/momo-air.png", stock: 0, threshold: 5 },
]

/**
 * Sample inventory table so the lowStockItems dynamic block renders in
 * previews. Generated by the same `lowStockItemsHtml` function used at send
 * time, for the same reason as `SAMPLE_ORDER_SUMMARY` above.
 */
export const SAMPLE_LOW_STOCK_ITEMS = lowStockItemsHtml(SAMPLE_LOW_STOCK_ITEMS_DATA)
