import type { Infographic } from "./infographics"

/** Engineer pack: the architecture, three real flows, and the test evidence. Full-size figures live on the "Architecture in Diagrams" docs page. */
export const engineerInfographics: Infographic[] = [
  {
    id: "infographic-engineer-architecture",
    kind: "layers",
    format: "carousel",
    pack: "engineer",
    eyebrow: "Architecture",
    title: "Four blocks, one direction.",
    summary: "Each block calls only the one below it. CI fails the build otherwise.",
    layers: [
      { name: "Routes", detail: "Pages, layouts and route handlers in app/" },
      { name: "Feature slices", detail: "One folder per domain, one public entry" },
      { name: "Shared lib", detail: "Database, auth and helpers. Never a feature" },
      { name: "Services", detail: "Neon, Stripe and Resend behind adapters" },
    ],
  },
  {
    id: "infographic-engineer-checkout",
    kind: "sequence",
    format: "carousel",
    pack: "engineer",
    eyebrow: "Checkout",
    title: "From cart to confirmation email.",
    summary: "The webhook, not the browser, decides an order is paid.",
    actors: ["Customer", "Store", "Stripe", "Resend"],
    steps: [
      { from: "Customer", to: "Store", label: "Check out the cart" },
      { from: "Store", to: "Stripe", label: "Create checkout session" },
      { from: "Customer", to: "Stripe", label: "Pay in embedded checkout" },
      { from: "Stripe", to: "Store", label: "Webhook finalises order once" },
      { from: "Store", to: "Resend", label: "Send order confirmation" },
      { from: "Resend", to: "Customer", label: "Confirmation email" },
    ],
  },
  {
    id: "infographic-engineer-restock",
    kind: "sequence",
    format: "carousel",
    pack: "engineer",
    eyebrow: "Back in stock",
    title: "Restock to alert, claimed once.",
    summary: "A claim stops double sends. A failed send hands it back.",
    actors: ["Admin", "Store", "Database", "Resend"],
    steps: [
      { from: "Admin", to: "Store", label: "Set stock above zero" },
      { from: "Store", to: "Database", label: "Save the new stock" },
      { from: "Store", to: "Database", label: "Claim waiting alerts once" },
      { from: "Store", to: "Resend", label: "Send back-in-stock email" },
      { from: "Resend", to: "Store", label: "Delivery result" },
      { from: "Store", to: "Database", label: "Release claim if send fails" },
    ],
  },
  {
    id: "infographic-engineer-theme",
    kind: "sequence",
    format: "carousel",
    pack: "engineer",
    eyebrow: "Theme",
    title: "One click, a new storefront theme.",
    summary: "Only the server action writes, and it checks the admin first.",
    actors: ["Admin", "Action", "Database", "Storefront"],
    steps: [
      { from: "Admin", to: "Action", label: "Activate a theme" },
      { from: "Action", to: "Database", label: "Save theme after admin check" },
      { from: "Action", to: "Storefront", label: "Revalidate cached pages" },
      { from: "Storefront", to: "Database", label: "Read the active theme" },
      { from: "Action", to: "Admin", label: "Theme is live" },
    ],
  },
  {
    id: "infographic-engineer-tests",
    kind: "bar-chart",
    format: "carousel",
    pack: "engineer",
    eyebrow: "Test pyramid",
    title: "Many fast tests, a few slow ones.",
    summary: "Counted on every run, widest layer first.",
    alt: "Horizontal bar chart of the test pyramid: unit tests first, then integration, smoke, accessibility and SEO browser tests.",
    bars: [
      { label: "Unit", value: { fact: "tests.unit" } },
      { label: "Integration", value: { fact: "tests.integration" } },
      { label: "Smoke", value: { fact: "tests.smoke" } },
      { label: "Accessibility", value: { fact: "tests.axe" } },
      { label: "SEO", value: { fact: "tests.seo" } },
    ],
  },
  {
    id: "infographic-engineer-coverage",
    kind: "before-after",
    format: "carousel",
    pack: "engineer",
    eyebrow: "Coverage ratchet",
    title: "Coverage can only go up.",
    summary: "CI fails if coverage drops below the committed baseline.",
    rows: [
      { label: "Lines covered", before: 35.7, after: { fact: "coverage.lines" }, note: "Baseline, then today" },
      { label: "Branches covered", before: 27.4, after: { fact: "coverage.branches" }, note: "Baseline, then today" },
    ],
  },
]
