import type { Infographic } from "./infographics"
import { buyerInfographics } from "./buyer-slides"
import { engineerInfographics } from "./engineer-slides"
import { recruiterInfographics } from "./recruiter-slides"

export const infographics: Infographic[] = [
  ...recruiterInfographics,
  ...buyerInfographics,
  ...engineerInfographics,
  {
    id: "infographic-stack",
    kind: "stack",
    format: "carousel",
    eyebrow: "The stack",
    title: "A modern stack, chosen for the long run.",
    summary: "Typed end to end, server first, every piece swappable.",
    groups: [
      {
        label: "Framework",
        items: [
          { name: "Next.js", version: "16", source: { pkg: "next", major: 16 } },
          { name: "React", version: "19", source: { pkg: "react", major: 19 } },
          { name: "TypeScript", source: { pkg: "typescript" } },
          { name: "Tailwind CSS", version: "4", source: { pkg: "tailwindcss", major: 4 } },
        ],
      },
      {
        label: "Data and auth",
        items: [
          { name: "Prisma", version: "6", source: { pkg: "prisma", major: 6 } },
          { name: "Neon", source: { file: "prisma/schema.prisma" } },
          { name: "Better Auth", source: { pkg: "better-auth" } },
          { name: "Zod", version: "4", source: { pkg: "zod", major: 4 } },
        ],
      },
      {
        label: "Payments and email",
        items: [
          { name: "Stripe", source: { pkg: "stripe" } },
          { name: "Resend", source: { file: "features/email/lib/adapters/sending/provider.ts" } },
        ],
      },
      {
        label: "Quality",
        items: [
          { name: "Vitest", source: { pkg: "vitest" } },
          { name: "Playwright", source: { pkg: "@playwright/test" } },
        ],
      },
    ],
  },
  {
    id: "infographic-layers",
    kind: "layers",
    format: "square",
    eyebrow: "Architecture",
    title: "Dependencies flow one way.",
    summary: "Each layer knows only the one beneath it. CI enforces it.",
    layers: [
      { name: "app", detail: "Routes, layouts and error boundaries" },
      { name: "features", detail: "One slice per domain, one public entry each" },
      { name: "features/*/lib", detail: "actions, data, domain, adapters" },
      { name: "lib", detail: "Shared code. Never imports a feature" },
    ],
  },
  {
    id: "infographic-before-after",
    kind: "before-after",
    format: "square",
    eyebrow: "Engineering health",
    title: "Measured, then fixed.",
    summary: "Four architecture numbers tracked in CI, before and after.",
    rows: [
      { label: "Deep imports across features", before: 116, after: { fact: "arch.deepImports" }, note: "One public entry per slice" },
      { label: "Shared code depending on features", before: 16, after: { fact: "arch.libToFeatures" }, note: "Dependencies point one way" },
      { label: "any types", before: 28, after: { fact: "arch.anyTypes" }, note: "Validated at every boundary" },
      { label: "useEffect calls", before: 55, after: { fact: "arch.useEffect" }, note: "Data loading moved to the server" },
    ],
  },
  {
    id: "infographic-tour-structure-overview",
    kind: "structure",
    area: "overview",
    format: "carousel",
    eyebrow: "What is in the box",
    title: "One repo, three front doors.",
    summary: "A storefront to shop, an admin to run it, docs to hand it over.",
  },
  {
    id: "infographic-tour-structure-storefront",
    kind: "structure",
    area: "storefront",
    format: "carousel",
    eyebrow: "Storefront",
    title: "What customers see.",
    summary: "Five sections, each opening on the pages beneath it.",
  },
  {
    id: "infographic-tour-structure-admin",
    kind: "structure",
    area: "admin",
    format: "carousel",
    eyebrow: "Admin",
    title: "What the owner sees.",
    summary: "Theme, catalogue, orders, customers and email, each with its screens.",
  },
  {
    id: "infographic-tour-structure-docs",
    kind: "structure",
    area: "docs",
    format: "carousel",
    eyebrow: "Documentation",
    title: "What teams inherit.",
    summary: "Guides grouped by who needs them; the owner's material stays gated.",
  },
  {
    id: "infographic-flow",
    kind: "flow",
    format: "carousel",
    eyebrow: "End to end",
    title: "From cart to confirmation email.",
    summary: "One flow, six steps, every one covered by tests.",
    steps: [
      { title: "Cart", detail: "Prices and quantities re-checked on the server" },
      { title: "Discount code", detail: "Validated and applied before payment" },
      { title: "Stripe payment", detail: "Hosted, secure and idempotent" },
      { title: "Webhook confirms", detail: "The order is finalised once, never twice" },
      { title: "Order saved", detail: "Stock updated and visible in the admin" },
      { title: "Confirmation email", detail: "Sent from an editable template" },
    ],
  },
  {
    id: "infographic-gates",
    kind: "gates",
    format: "square",
    eyebrow: "Quality gates",
    title: "Nothing merges unless all seven pass.",
    summary: "Every pull request runs the same pipeline, then a real preview build.",
    steps: [
      { name: "Typecheck", detail: "Strict TypeScript" },
      { name: "Lint", detail: "Boundary rules included" },
      { name: "Arch", detail: "Architecture ratchet" },
      { name: "Unit", detail: "Pure logic and docs guards" },
      { name: "Integration", detail: "Database-backed flows" },
      { name: "Smoke", detail: "Real browser journeys" },
      { name: "Axe", detail: "Accessibility checks" },
    ],
  },
  {
    id: "infographic-offer",
    kind: "offer",
    format: "carousel",
    eyebrow: "Work with me",
    title: "A working store, made yours.",
    summary: "Start from a tested template, spend time on what sets you apart.",
    columns: [
      {
        heading: "Included",
        items: [
          "Storefront with product pages",
          "Checkout with Stripe test mode",
          "Admin for orders and customers",
          "Email campaigns and templates",
          "Discount codes and offers",
        ],
      },
      {
        heading: "Customised for you",
        items: ["Your brand, theme and fonts", "Your products and catalog", "Your domain and email sender", "Your Stripe and Resend accounts"],
      },
      {
        heading: "Handover",
        items: ["Written handover guide", "Local runbook and environment guide", "Tests and CI left green", "Docs site your team can extend"],
      },
    ],
  },
  {
    id: "infographic-table",
    kind: "table",
    format: "carousel",
    eyebrow: "Testing",
    title: "Every layer tested its own way.",
    summary: "Fast checks on pure rules first, real browsers last.",
    columns: ["Layer", "Tool", "What it proves"],
    rows: [
      { label: "Unit", cells: ["Vitest", "Pure rules and guards"] },
      { label: "Integration", cells: ["Vitest", "Flows against a real database"] },
      { label: "Smoke", cells: ["Playwright", "Journeys in a real browser"] },
      { label: "Axe", cells: ["Playwright", "Accessibility on key pages"] },
      { label: "SEO", cells: ["Playwright", "Search metadata"] },
    ],
  },
  {
    id: "infographic-bar-chart",
    kind: "bar-chart",
    format: "story",
    eyebrow: "Test suite",
    title: "Tests at every layer.",
    summary: "Counted on each run, never typed in by hand.",
    alt: "Horizontal bar chart of automated test counts by layer: unit, integration, smoke, accessibility and SEO.",
    unit: "tests",
    bars: [
      { label: "Unit", value: { fact: "tests.unit" } },
      { label: "Integration", value: { fact: "tests.integration" } },
      { label: "Smoke", value: { fact: "tests.smoke" } },
      { label: "Accessibility", value: { fact: "tests.axe" } },
      { label: "SEO", value: { fact: "tests.seo" } },
    ],
  },
  {
    id: "infographic-line-chart",
    kind: "line-chart",
    format: "square",
    illustrative: true,
    eyebrow: "Total cost",
    title: "A tested base keeps costs flatter.",
    summary: "The shape of total cost over three years.",
    alt: "Illustrative line chart: total cost from scratch climbs steeply over three years, while a tested template starts lower and rises gently.",
    xLabels: ["Launch", "Year one", "Year two", "Year three"],
    series: [
      { name: "From scratch", values: [6, 8, 10, 12] },
      { name: "Template", values: [2, 3, 4, 5] },
    ],
  },
  {
    id: "infographic-sequence",
    kind: "sequence",
    format: "carousel",
    eyebrow: "Back in stock",
    title: "From sold out to back in their inbox.",
    summary: "One alert per email, claimed once when stock returns.",
    actors: ["Customer", "Store", "Database", "Resend"],
    steps: [
      { from: "Customer", to: "Store", label: "Notify me when it is back" },
      { from: "Store", to: "Database", label: "Save one alert per email" },
      { from: "Store", to: "Database", label: "Restock claims alerts once" },
      { from: "Store", to: "Resend", label: "Send back-in-stock email" },
      { from: "Resend", to: "Customer", label: "Email with a product link" },
      { from: "Customer", to: "Store", label: "One-click unsubscribe" },
    ],
  },
]

export function getInfographic(id: string): Infographic | undefined {
  return infographics.find((i) => i.id === id)
}
