import type { Doc } from "../lib/domain/schema"

/**
 * Full-size versions of the engineer pack slides. qa/unit/docs/engineer-diagrams.test.ts
 * checks every slide actor and step appears here, in order, so slide and docs agree.
 */
export const architectureInDiagrams: Doc = {
  slug: "architecture-in-diagrams",
  title: "Architecture in Diagrams",
  category: "Architecture",
  audience: "developer",
  access: "public",
  summary:
    "The four-block architecture and three real flows (checkout, back in stock, theme activation) as full-size diagrams. They match the engineer slide pack step for step, with the extra detail a slide has no room for.",
  readingMinutes: 6,
  order: 2,
  updatedAt: "2026-10-06",
  tags: ["architecture", "diagrams", "sequence", "checkout", "stock alerts", "theme", "engineer"],
  body: [
    {
      type: "paragraph",
      text: "Each diagram below is the full version of a slide in the engineer pack. The slides are trimmed to four actors and six steps; these figures keep every step. A unit test fails if a slide step goes missing from its figure, so the two cannot drift apart.",
    },
    { type: "heading", text: "Four blocks, one direction" },
    {
      type: "mermaid",
      kind: "architecture",
      title: "Four blocks, one direction",
      caption: "Arrows show the only allowed imports. The architecture audit in CI fails any import that points back up.",
      diagram: [
        "flowchart TD",
        '  subgraph routes["Routes"]',
        "    pages[app/ pages and layouts]",
        "    handlers[Route handlers: Stripe webhook]",
        "  end",
        '  subgraph slices["Feature slices"]',
        "    entry[features/*/index.ts public entry]",
        "    inner[actions, data, domain, adapters]",
        "  end",
        '  subgraph shared["Shared lib"]',
        "    db[Prisma client]",
        "    auth[Better Auth session]",
        "  end",
        '  subgraph services["Services"]',
        "    neon[(Neon Postgres)]",
        "    stripe[Stripe]",
        "    resend[Resend]",
        "  end",
        "  routes --> slices",
        "  slices --> shared",
        "  shared --> services",
        "  slices --> services",
      ].join("\n"),
    },
    { type: "heading", text: "Checkout to confirmation email" },
    {
      type: "mermaid",
      kind: "sequence",
      title: "Checkout to confirmation email",
      caption: "The order is only marked paid when the signed webhook arrives, and finalising is idempotent so a retried webhook does nothing.",
      diagram: [
        "sequenceDiagram",
        "  participant C as Customer",
        "  participant S as Store",
        "  participant DB as Database",
        "  participant ST as Stripe",
        "  participant R as Resend",
        "  C->>S: Check out the cart",
        "  S->>DB: Reserve stock, create pending order",
        "  S->>ST: Create checkout session",
        "  ST-->>S: Client secret",
        "  C->>ST: Pay in embedded checkout",
        "  ST->>S: Webhook finalises order once",
        "  S->>DB: Mark order paid",
        "  S->>R: Send order confirmation",
        "  R->>C: Confirmation email",
      ].join("\n"),
    },
    { type: "heading", text: "Restock to back-in-stock alert" },
    {
      type: "mermaid",
      kind: "sequence",
      title: "Restock to back-in-stock alert",
      caption: "Claiming alerts in the database means two restocks at once cannot email the same person twice. A failed send releases the claim for the next restock.",
      diagram: [
        "sequenceDiagram",
        "  participant A as Admin",
        "  participant S as Store",
        "  participant DB as Database",
        "  participant R as Resend",
        "  A->>S: Set stock above zero",
        "  S->>S: Re-check admin role",
        "  S->>DB: Save the new stock",
        "  S->>DB: Claim waiting alerts once",
        "  DB-->>S: Claimed alerts",
        "  S->>R: Send back-in-stock email",
        "  R-->>S: Delivery result",
        "  S->>DB: Release claim if send fails",
      ].join("\n"),
    },
    { type: "heading", text: "Theme activation" },
    {
      type: "mermaid",
      kind: "sequence",
      title: "Theme activation",
      caption: "The admin page only builds the next theme state. The server action is the one place that writes it.",
      diagram: [
        "sequenceDiagram",
        "  participant A as Admin",
        "  participant SA as Action",
        "  participant DB as Database",
        "  participant SF as Storefront",
        "  A->>SA: Activate a theme",
        "  SA->>SA: Re-check admin role",
        "  SA->>DB: Save theme after admin check",
        "  DB-->>SA: Saved",
        "  SA->>SF: Revalidate cached pages",
        "  SF->>DB: Read the active theme",
        "  SA-->>A: Theme is live",
      ].join("\n"),
    },
    {
      type: "paragraph",
      text: "Source for the slides: features/showcase/lib/domain/engineer-slides.ts. Test counts and coverage on the slides come from the latest run of pnpm facts, never typed in.",
    },
  ],
}
