import type { Doc } from "../schema"

export const authenticationAndAccess: Doc = {
  slug: "authentication-and-access-control",
  title: "Authentication & Authorization",
  category: "Security & Auth",
  audience: "developer",
  access: "admin",
  summary:
    "How sign-in, sessions, roles, server-side guards, and doc gating fit together. Authentication is now server-enforced with Better Auth on Neon — sessions are real, roles are verified on the server, and admin bodies never reach a non-admin browser.",
  readingMinutes: 12,
  order: 1,
  updatedAt: "2026-09-26",
  tags: ["auth", "authorization", "security", "better auth", "sessions", "roles", "route guard", "gating"],
  body: [
    {
      type: "paragraph",
      text: "Access control runs through one auth instance and a small set of guards, so every protected surface — the account area, the admin dashboard, the gated docs, and every write action — enforces the same rules the same way. Authentication is handled by Better Auth backed by Neon Postgres: passwords are hashed, sessions are issued as cookies, and the session is verified on the server on every protected render.",
    },
    {
      type: "callout",
      variant: "success",
      title: "This is now a real security boundary",
      text: "An earlier version of the app derived the role client-side from localStorage. That is no longer true. Sessions and roles are verified server-side by Better Auth on Neon, and admin-only write actions re-check the role before touching the database.",
    },
    {
      type: "heading",
      text: "The moving parts",
    },
    {
      type: "table",
      headers: ["Piece", "Lives in", "Responsibility"],
      rows: [
        ["Auth instance", "lib/auth.ts", "Better Auth config: email + password, sessions, autoSignIn, Neon adapter."],
        ["Role derivation", "lib/auth/config.ts", "effectiveRole() resolves admin from an email allowlist or a persisted roleOverride."],
        ["Client hook", "the auth client", "Exposes session/status and sign-in/out to client islands."],
        ["Route guard", "account layout", "Redirects unauthenticated visitors to sign-in."],
        ["Admin guard", "admin route-group layout", "Additionally requires the admin role, server-verified."],
        ["Server actions", "features/*/*-actions.ts", "Re-check the role server-side before any privileged write."],
        ["Doc gating", "features/docs/api", "canViewDoc decides whether a doc body is serialized to the browser at all."],
      ],
    },
    {
      type: "heading",
      text: "How sign-in flows",
    },
    {
      type: "mermaid",
      kind: "sequence",
      title: "Figure 1 — Email + password sign-in",
      caption: "Better Auth verifies the credential against Neon, issues a session cookie, and autoSignIn drops the user straight into an authenticated session.",
      diagram: [
        "sequenceDiagram",
        "  participant U as User",
        "  participant C as Client (auth client)",
        "  participant A as Better Auth handler",
        "  participant DB as Neon (user/account/session)",
        "  U->>C: submit email + password",
        "  C->>A: POST sign-in",
        "  A->>DB: look up account, verify password hash",
        "  DB-->>A: user row",
        "  A->>DB: create session",
        "  A-->>C: Set-Cookie: session",
        "  C-->>U: redirect to /account (authenticated)",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "Authorization: how admin is decided",
    },
    {
      type: "paragraph",
      text: "Authentication answers 'who are you'; authorization answers 'what may you do'. Admin is never a client-set flag. effectiveRole() derives it on the server from two inputs: an email allowlist (configurable, defaulting to the operator addresses) and an optional roleOverride column persisted on the user. If either says admin, the user is admin — otherwise they are a customer.",
    },
    {
      type: "code",
      language: "typescript",
      title: "lib/auth/config.ts — role derivation (shape)",
      code: [
        "// Admin is resolved server-side, never trusted from the client.",
        "export function effectiveRole(user: {",
        "  email?: string | null",
        "  roleOverride?: string | null",
        "}): 'admin' | 'customer' {",
        "  if (user.roleOverride === 'admin') return 'admin'",
        "  if (user.email && ADMIN_ALLOWLIST.includes(user.email.toLowerCase())) {",
        "    return 'admin'",
        "  }",
        "  return 'customer'",
        "}",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "The authorization matrix",
    },
    {
      type: "table",
      headers: ["Surface", "Anonymous", "Customer", "Admin"],
      rows: [
        ["Storefront, product pages", "View", "View", "View"],
        ["Public user-guide docs", "Read", "Read", "Read"],
        ["Account area", "Redirect to sign-in", "Full", "Full"],
        ["Admin dashboard", "Redirect", "Redirect to storefront", "Full"],
        ["Admin / developer doc bodies", "Summary only", "Summary only", "Full body"],
        ["Catalog / settings / email writes", "Blocked", "Blocked", "Allowed (re-checked in action)"],
      ],
    },
    {
      type: "heading",
      text: "The access decision, every protected render",
    },
    {
      type: "mermaid",
      kind: "flow",
      title: "Figure 2 — Access decision",
      caption: "Guards run this before a protected page renders; server actions run the same role check before writing.",
      diagram: [
        "flowchart TD",
        "  A[Request protected surface] --> B{Valid session?}",
        "  B -- No --> C[Redirect to /sign-in]",
        "  B -- Yes --> D{Admin required?}",
        "  D -- No --> E[Render / allow]",
        "  D -- Yes --> F{effectiveRole = admin?}",
        "  F -- No --> G[Redirect to storefront / reject action]",
        "  F -- Yes --> E[Render / allow]",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "Doc gating is a data decision, not a UI trick",
    },
    {
      type: "paragraph",
      text: "Gated docs are not merely hidden with CSS. For a non-admin viewer, the doc body is never serialized into the payload — only the card summary is. Admin guide content cannot be recovered from view-source or the network tab, because it was never sent. The same effectiveRole check that guards the dashboard decides whether canViewDoc returns the body.",
    },
    {
      type: "callout",
      variant: "info",
      title: "Defense in depth",
      text: "Two independent layers protect admin content: the route/action guard (you cannot reach the surface) and body-stripping (even if you request the doc route, a non-admin receives only the summary). Neither depends on the client being honest.",
    },
    {
      type: "heading",
      text: "Sign-out from a guarded page",
    },
    {
      type: "paragraph",
      text: "This is the subtle one. Signing out ends the session. If you are standing on a guarded page (account or admin) when that happens, the route guard's effect fires and wants to send you to /sign-in — which is not where a signed-out shopper should land.",
    },
    {
      type: "steps",
      items: [
        { title: "The race", text: "A client-side router.replace('/') from the sign-out handler competes with the guard's redirect to /sign-in, and the guard tends to win." },
        { title: "The fix", text: "Sign-out uses a hard window.location.replace('/'), which unloads the guarded page immediately so the guard never gets to redirect." },
        { title: "The bonus", text: "A full navigation also clears client session state cleanly, avoiding any stale-session flicker." },
      ],
    },
    {
      type: "callout",
      variant: "warning",
      title: "Rule of thumb",
      text: "Redirect after an auth state change with a real navigation, not a client push, when the current route is itself guarded by that same state. Otherwise the guard and your handler fight over the destination.",
    },
    {
      type: "heading",
      text: "The auth tables on Neon",
    },
    {
      type: "mermaid",
      kind: "er",
      title: "Figure 3 — Better Auth schema (Neon)",
      caption: "Standard Better Auth tables. roleOverride lives on user; everything else is issued and managed by Better Auth.",
      diagram: [
        "erDiagram",
        "  USER ||--o{ ACCOUNT : has",
        "  USER ||--o{ SESSION : has",
        "  USER {",
        "    string id PK",
        "    string email",
        "    boolean emailVerified",
        "    string roleOverride",
        "    datetime createdAt",
        "  }",
        "  ACCOUNT {",
        "    string id PK",
        "    string userId FK",
        "    string providerId",
        "    string password",
        "  }",
        "  SESSION {",
        "    string id PK",
        "    string userId FK",
        "    string token",
        "    datetime expiresAt",
        "  }",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "What still changes with Strapi",
    },
    {
      type: "paragraph",
      text: "Authentication is already server-side, so the CMS move is not an auth rewrite. What Strapi adds is content authorship: editors get their own roles inside Strapi, while the app keeps its Better Auth sessions for shoppers and operators. The access field on each doc and the effectiveRole concept stay exactly as they are — the doc bodies simply come from the CMS instead of the code seed.",
    },
  ],
}
