import type { Doc } from "../schema"

export const dataLayerAndDatabase: Doc = {
  slug: "data-layer-and-database",
  title: "Data Layer & Database",
  category: "Data & Analytics",
  audience: "developer",
  access: "admin",
  summary:
    "Every piece of business data now lives in Neon Postgres via Prisma, reached through a port/adapter seam. This guide is the schema map, the merge-on-read catalog model, the transactional stock/order write path, and the cache-revalidation strategy — the ground truth for the Strapi migration.",
  readingMinutes: 13,
  order: 1,
  updatedAt: "2026-09-26",
  tags: ["database", "neon", "prisma", "postgres", "ports and adapters", "transactions", "caching", "ssr"],
  body: [
    {
      type: "paragraph",
      text: "The app is fully server-backed: catalog, orders, reviews, auth, the email system, and store settings all persist in Neon. The only intentional exceptions are the shopping cart (anonymous pre-checkout state) and the theme preference (a device setting) — both correctly client-side. This guide covers how that data is shaped, read, and written.",
    },
    {
      type: "heading",
      text: "What lives where",
    },
    {
      type: "table",
      headers: ["Domain", "Storage", "Model / notes"],
      rows: [
        ["Catalog", "Neon + code seed", "Seed provides marketing copy; ProductOverlay stores admin-managed price/stock/name and tombstones."],
        ["Orders", "Neon", "Created transactionally with the stock decrement."],
        ["Reviews", "Neon", "Neon-backed provider behind the reviews port."],
        ["Auth", "Neon (Better Auth)", "user / account / session tables; role via allowlist + roleOverride."],
        ["Email system", "Neon", "settings, templates, campaigns, log, presets, messages, subscribers."],
        ["Store settings", "Neon", "StoreSettings singleton (id = 1) with discrete typed columns."],
        ["Cart", "Client", "Anonymous pre-checkout state; persists to Neon only when an order is placed."],
        ["Theme", "Client", "Device-level preference (next-themes), not business data."],
      ],
    },
    {
      type: "heading",
      text: "The core schema",
    },
    {
      type: "mermaid",
      kind: "er",
      title: "Figure 1 — Business tables (Neon)",
      caption: "The catalog overlay, orders, and the store-settings singleton. Auth and email tables are covered in their own guides.",
      diagram: [
        "erDiagram",
        "  PRODUCT_OVERLAY {",
        "    string slug PK",
        "    json data",
        "    boolean deleted",
        "    datetime updatedAt",
        "  }",
        "  ORDER ||--o{ ORDER_ITEM : contains",
        "  ORDER {",
        "    string id PK",
        "    string email",
        "    int totalMinor",
        "    string status",
        "    datetime createdAt",
        "  }",
        "  ORDER_ITEM {",
        "    string id PK",
        "    string orderId FK",
        "    string productSlug",
        "    int quantity",
        "    int unitPriceMinor",
        "  }",
        "  STORE_SETTINGS {",
        "    int id PK",
        "    string storeName",
        "    string companyName",
        "    string currency",
        "    int lowStockThreshold",
        "    boolean emailAlerts",
        "    boolean onboarded",
        "  }",
      ].join("\n"),
    },
    {
      type: "callout",
      variant: "note",
      title: "Why discrete columns, not a JSON blob",
      text: "StoreSettings uses one row of typed columns rather than a JSON bag. This is deliberate: discrete columns map 1:1 onto a Strapi single-type's fields, so the CMS migration is a field-for-field translation instead of an unpack-and-reshape job.",
    },
    {
      type: "heading",
      text: "The port/adapter seam",
    },
    {
      type: "paragraph",
      text: "The UI never imports Prisma. It calls a port — a typed domain function — and an adapter behind that port decides where the data comes from. Today most adapters read Neon with the code seed as a fallback; after the migration, a doc/article adapter will read Strapi instead. The port signature never changes, so the pages never change.",
    },
    {
      type: "code",
      language: "typescript",
      title: "The shape of a port call (catalog)",
      code: [
        "// A Server Component reads through the port — no SQL in sight.",
        "import { getCatalog } from '@/features/catalog'",
        "",
        "export default async function ProductsPage() {",
        "  const products = await getCatalog() // seed merged with Neon overlay",
        "  return <ProductGrid products={products} />",
        "}",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "Merge-on-read: the catalog model",
    },
    {
      type: "paragraph",
      text: "Products have two sources of truth by design. Marketing content (hero copy, feature beats, specs) stays in the code seed where it is version-controlled and reviewed. The admin-managed layer (price, stock, name, created products, deletions) lives in the ProductOverlay table. At read time the adapter merges them: the overlay wins field-by-field, and a row flagged deleted tombstones a seed product so it disappears from the store.",
    },
    {
      type: "mermaid",
      kind: "flow",
      title: "Figure 2 — Catalog merge",
      caption: "Read = seed ⊕ overlay. Admin writes only ever touch the overlay; the seed is immutable at runtime.",
      diagram: [
        "flowchart LR",
        "  SEED[Code seed: marketing copy + defaults] --> MERGE{Merge by slug}",
        "  OVL[(ProductOverlay: price, stock, name, deleted)] --> MERGE",
        "  MERGE --> OUT[Effective catalog]",
        "  OUT --> STORE[Storefront]",
        "  OUT --> ADMIN[Admin catalog table]",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "The transactional write path",
    },
    {
      type: "paragraph",
      text: "Anything involving stock or money is transactional. Placing an order does not first check stock and then insert — that races. Instead the order insert and the stock decrement happen in one Prisma transaction with the oversell guard enforced inside it, so two shoppers competing for the last unit cannot both succeed.",
    },
    {
      type: "mermaid",
      kind: "sequence",
      title: "Figure 3 — Checkout order + stock decrement",
      caption: "One transaction. If the decrement would drive stock negative, the whole thing rolls back and nothing is charged or recorded.",
      diagram: [
        "sequenceDiagram",
        "  participant C as Checkout (client island)",
        "  participant SA as createOrder (server action)",
        "  participant TX as Prisma transaction",
        "  participant DB as Neon",
        "  C->>SA: place order (cart)",
        "  SA->>TX: begin",
        "  TX->>DB: decrement stock WHERE stock >= qty",
        "  alt insufficient stock",
        "    DB-->>TX: 0 rows affected",
        "    TX-->>SA: rollback",
        "    SA-->>C: oversell error (nothing charged)",
        "  else ok",
        "    TX->>DB: insert order + items",
        "    TX-->>SA: commit",
        "    SA-->>C: order confirmed",
        "  end",
      ].join("\n"),
    },
    {
      type: "callout",
      variant: "warning",
      title: "Never split a check from its mutation",
      text: "A read-then-write ('is there stock? ok, now subtract') is a classic race. Make the guard part of the write — a conditional UPDATE that only succeeds when the invariant holds — and let the transaction roll back otherwise.",
    },
    {
      type: "heading",
      text: "SSR seed + optimistic client reconcile",
    },
    {
      type: "paragraph",
      text: "Data-backed client providers (catalog, settings) follow one pattern so the first paint is correct and writes feel instant. The server seeds the provider with the authoritative Neon value during SSR, so the first client render matches the server exactly — no flash of defaults, no hydration mismatch. On a write, the provider updates optimistically, writes through to Neon, then reconciles with the returned row.",
    },
    {
      type: "steps",
      items: [
        { title: "SSR seed", text: "The layout reads Neon and passes the value into the provider, so hydration starts from server truth." },
        { title: "Optimistic write", text: "The provider updates in memory immediately so the UI responds without waiting for the round-trip." },
        { title: "Write-through + reconcile", text: "The server action persists to Neon and returns the saved row; the provider adopts it, healing any drift." },
      ],
    },
    {
      type: "heading",
      text: "Connections: pooled vs. direct",
    },
    {
      type: "table",
      headers: ["Use", "URL", "Why"],
      rows: [
        ["App runtime queries", "Pooled (DATABASE_URL)", "Serverless functions open many short-lived connections; the pooler absorbs them."],
        ["Migrations / schema push", "Direct (DATABASE_URL_UNPOOLED)", "DDL needs a stable single session the pooler should not multiplex."],
      ],
    },
    {
      type: "callout",
      variant: "tip",
      title: "After a schema change",
      text: "prisma db push (or migrate) updates Neon, then prisma generate rewrites the client. The running dev server holds the old client in memory — restart it so it loads the regenerated client, or you will see 'model is undefined' errors against a table that really does exist.",
    },
    {
      type: "heading",
      text: "Cache & revalidation",
    },
    {
      type: "paragraph",
      text: "Reads are cached and tagged so a write can surgically invalidate just what changed. The docs layer, for example, tags each doc read with both a broad docs tag and a granular doc:<slug> tag, so editing one guide revalidates that guide without dumping the whole library's cache. The same discipline applies as more content moves behind the CMS seam.",
    },
    {
      type: "list",
      items: [
        "Tag reads at the granularity you will want to invalidate (per-entity, not just per-collection).",
        "Revalidate the specific tag inside the write action, right after the successful mutation.",
        "Use ISR (time-based revalidate) as a backstop so externally-authored content still refreshes without a deploy.",
      ],
    },
    {
      type: "heading",
      text: "Where to go next",
    },
    {
      type: "list",
      items: [
        "System Architecture Overview — how this data seam sits inside the whole app.",
        "Authentication & Authorization — how the auth tables and server-side role checks guard every write here.",
        "The Strapi Migration Runbook & Content Modeling — how these discrete schemas map onto CMS types.",
      ],
    },
  ],
}
