import type { Doc } from "../schema"

export const emailPlatformArchitecture: Doc = {
  slug: "email-platform-architecture",
  title: "Email Platform Architecture",
  category: "Architecture",
  audience: "developer",
  access: "public",
  summary:
    "How the block-based email editor works under the hood: the Neon tables, the save path with lock checks and version snapshots, the template lifecycle, saved sections, starters, and how a campaign gets sent, both manually and on a schedule.",
  readingMinutes: 12,
  order: 2,
  updatedAt: "2026-10-02",
  tags: ["email", "architecture", "templates", "versions", "locks", "campaigns", "resend", "prisma"],
  body: [
    {
      type: "paragraph",
      text: "Email templates are stored as an ordered list of typed blocks (heading, text, image, button, product picks and more) in a JSON column. The editor, the live preview and the sender all use the same renderer, so what an admin sees is what customers receive. This guide maps the moving parts. The in-app Email Templates guide covers the same features from the editor's point of view.",
    },
    {
      type: "heading",
      text: "Modules and their one job",
    },
    {
      type: "table",
      headers: ["Module", "Responsibility"],
      rows: [
        ["features/email/blocks", "Block types and the renderer shared by preview and send"],
        ["features/email/repo.ts", "Prisma reads and writes for templates, versions, sections and campaigns"],
        ["features/email/admin-actions.ts", "Server actions; each starts with requireAdmin()"],
        ["features/email/locks.ts", "Pure lock rules: where new blocks go, lockViolations()"],
        ["features/email/versions.ts", "Snapshot and retention rules for template history"],
        ["features/email/sections.ts", "Saved-section validation and fresh ids on insert"],
        ["features/email/starters.ts", "Starter gallery (Essentials and Seasonal campaigns)"],
        ["features/email/campaign-send.ts", "Server-only send used by both Send now and the scheduler"],
        ["lib/auth/permissions.ts", "canLockBlocks, assertAdmin and the proxy gate decision"],
      ],
    },
    {
      type: "heading",
      text: "The data model",
    },
    {
      type: "mermaid",
      kind: "er",
      title: "Figure 1 — Email tables on Neon",
      caption: "Templates own their version history (deleted with the template). Saved sections are independent: inserting one copies its blocks, so deleting a section never changes a template.",
      diagram: [
        "erDiagram",
        "  EMAIL_TEMPLATE ||--o{ EMAIL_TEMPLATE_VERSION : \"has history\"",
        "  EMAIL_TEMPLATE ||--o{ CAMPAIGN : \"used by\"",
        "  EMAIL_TEMPLATE {",
        "    int id PK",
        "    string key UK",
        "    string category",
        "    json blocks",
        "    bool isSystem",
        "    int version",
        "  }",
        "  EMAIL_TEMPLATE_VERSION {",
        "    int id PK",
        "    int templateId FK",
        "    int version",
        "    json blocks",
        "    string reason",
        "  }",
        "  CAMPAIGN {",
        "    int id PK",
        "    int templateId FK",
        "    json audience",
        "    string status",
        "    datetime scheduledAt",
        "  }",
        "  EMAIL_SECTION {",
        "    int id PK",
        "    string name",
        "    json blocks",
        "  }",
        "  EMAIL_LOG {",
        "    int id PK",
        "    string templateKey",
        "    string type",
        "    string status",
        "  }",
        "  EMAIL_SETTINGS {",
        "    int id PK",
        "    string brandName",
        "    string accentColor",
        "  }",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "Saving a template",
    },
    {
      type: "mermaid",
      kind: "sequence",
      title: "Figure 2 — Save with lock checks and a version snapshot",
      caption: "Reset and Restore follow the same path. The lock check compares the stored blocks with the incoming ones, so a crafted request can't bypass the editor.",
      diagram: [
        "sequenceDiagram",
        "  participant E as Editor (client)",
        "  participant PX as proxy.ts",
        "  participant SA as updateTemplate action",
        "  participant PM as permissions.ts",
        "  participant LK as locks.ts",
        "  participant DB as Neon",
        "  E->>PX: POST /admin/email/templates/:id",
        "  PX->>PM: adminGateDecision(session)",
        "  PM-->>PX: allow",
        "  PX->>SA: forward",
        "  SA->>PM: requireAdmin()",
        "  SA->>DB: load current blocks",
        "  SA->>PM: canLockBlocks(viewer)?",
        "  alt not a locker",
        "    SA->>LK: lockViolations(current, incoming)",
        "    LK-->>SA: [] or violations",
        "    SA-->>E: refuse if any violation",
        "  end",
        "  SA->>DB: update template, version + 1",
        "  SA->>DB: insert version snapshot (reason: save)",
        "  SA-->>E: saved template",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "Template lifecycle",
    },
    {
      type: "mermaid",
      kind: "state",
      title: "Figure 3 — From starter to sent",
      caption: "Every arrow that changes content writes a version snapshot, so any state can be restored.",
      diagram: [
        "stateDiagram-v2",
        "  [*] --> Draft: New from starter, blank or duplicate",
        "  Draft --> Draft: Edit + Save (snapshot)",
        "  Draft --> Draft: Insert saved section",
        "  Draft --> Draft: Lock or unlock block (lockers only)",
        "  Draft --> Restored: Restore older version",
        "  Restored --> Draft: continue editing",
        "  Draft --> Original: Reset (system templates)",
        "  Original --> Draft: continue editing",
        "  Draft --> InCampaign: chosen for a campaign",
        "  InCampaign --> Sent: Send now or schedule",
        "  Sent --> [*]",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "Locked blocks",
    },
    {
      type: "list",
      items: [
        "A block with locked: true can't be edited, moved, deleted or dragged by an admin who isn't allowed to lock.",
        "New blocks and inserted sections go after a leading run of locked blocks (such as a brand header), or at the end if every block is locked.",
        "lockViolations(before, after) reports any locked block that was changed, removed or newly locked or unlocked. The server refuses the save unless canLockBlocks is true.",
        "The editor gets a canLock flag from the server page. Admins who can't lock see a Locked badge instead of the toggle.",
      ],
    },
    {
      type: "heading",
      text: "Sending a campaign",
    },
    {
      type: "mermaid",
      kind: "flow",
      title: "Figure 4 — Two entry points, one sender",
      caption: "Send now runs as a signed-in admin; the scheduler runs with no session. Both call the same server-only sendCampaign.",
      diagram: [
        "flowchart TD",
        "  A[Admin clicks Send now] --> B[sendCampaignAction: requireAdmin]",
        "  C[Cron GET /api/cron/send-scheduled-campaigns] --> D{CRON_SECRET set and matches?}",
        "  D -- No --> X[501 or 401]",
        "  D -- Yes --> E[listDueCampaigns]",
        "  B --> S[sendCampaign]",
        "  E --> S",
        "  S --> F[status: sending]",
        "  F --> G[Render blocks per recipient]",
        "  G --> H[Resend API]",
        "  H --> I[(EmailLog rows)]",
        "  I --> J[status: sent + stats]",
      ].join("\n"),
    },
    {
      type: "callout",
      variant: "note",
      title: "Scheduler status",
      text: "The cron route exists and is tested, but there is no crons entry in vercel.json yet. The Hobby plan only allows daily runs, so campaigns are sent with Send now for the time being. To enable it, add the crons entry and set CRON_SECRET.",
    },
    {
      type: "heading",
      text: "Testing approach",
    },
    {
      type: "table",
      headers: ["Area", "Unit tests (pure rules)", "Integration tests (actions)"],
      rows: [
        ["Locks", "Insert position, lockViolations", "Non-locker save, reset, restore refused"],
        ["Versions", "Snapshot reasons, retention", "Reset to original, restore adds a version"],
        ["Sections", "Order, fresh ids, name and size limits", "Covered through the editor actions"],
        ["Starters", "Groups, unique keys, valid blocks", "Created template matches starter"],
        ["Permissions", "Owner, locker, admin, customer, signed out", "requireAdmin on every action"],
      ],
    },
  ],
}
