import type { Doc } from "../lib/domain/schema"

export const socialLaunchKit: Doc = {
  slug: "social-launch-kit",
  title: "Social Launch Kit: Email Builder & Permissions",
  category: "Positioning",
  audience: "owner",
  access: "owner",
  summary:
    "Ready-to-post copy for LinkedIn, a Facebook business page, Telegram and X covering the email builder, seasonal campaigns, defence-in-depth permissions and the documentation programme. Each post is paired with an image already in the repo and a link that previews well when shared.",
  readingMinutes: 8,
  order: 3,
  updatedAt: "2026-10-06",
  tags: ["social", "linkedin", "facebook", "telegram", "launch", "recruitment", "marketing"],
  body: [
    {
      type: "callout",
      variant: "info",
      title: "Before you post",
      text: "Replace [live URL] with the deployed site. Every /docs page now generates its own link preview image, so pasting a docs link into LinkedIn, Facebook or Telegram shows a branded card with the page title. Post the case study link rather than the homepage when the audience is a hiring manager or CTO.",
    },
    { type: "heading", text: "Demo clip" },
    {
      type: "paragraph",
      text: "A 30-second muted MP4 (1280×720, H.264) that LinkedIn, Facebook, X and Telegram all play inline. Download it from /showcase/video/storefront.mp4 and upload it natively rather than linking, because native video gets far more reach. Re-record it after UI changes with pnpm showcase:video.",
    },
    {
      type: "video",
      src: "/showcase/video/storefront.mp4",
      poster: "/showcase/video/storefront.jpg",
      description:
        "Screen recording of the storefront: the home page scroll animation plays, a product is opened from the shop, added to the cart, and the cart drawer shows the item and subtotal.",
      caption: "Storefront journey clip for social posts.",
    },
    { type: "heading", text: "Carousel and square images" },
    {
      type: "paragraph",
      text: "An 8-slide LinkedIn carousel (1080×1350) and three 1080×1080 squares in the AduDev brand, with the Momo Audio screenshots kept in their own branding. The closing slide carries a QR code to the case study. Each slide also ships as a PNG for channels without document posts. Re-export after copy or design changes with pnpm showcase:assets.",
    },
    {
      type: "image",
      src: "/showcase/social/carousel-cover.png",
      alt: "Carousel cover slide: 'Email built into the store, not bolted on.' above the Christmas campaign email.",
      caption: "Carousel cover slide.",
      width: 1080,
      height: 1350,
    },
    {
      type: "image",
      src: "/showcase/social/carousel-flow.png",
      alt: "Carousel slide showing the flow from the checkout action to a Stripe payment, a signed webhook, the saved order and the Resend order email.",
      caption: "Checkout to inbox. The new flow slide.",
      width: 1080,
      height: 1350,
    },
    { type: "heading", text: "Infographics" },
    {
      type: "paragraph",
      text: "Eleven developer and CTO-minded infographics, rendered from the same tokens as the slides: portrait 1080×1350, square 1080×1080 and one 1080×1920 story. Measured numbers are read from .generated/facts.json when the slide renders, so they cannot drift from the code. A chart with typed numbers must be marked illustrative, and the slide prints that word. Re-export with pnpm showcase:assets.",
    },
    {
      type: "image",
      src: "/showcase/social/infographic-stack.png",
      alt: "Infographic listing the stack: Next.js, React, TypeScript, Prisma on Neon, Better Auth, Stripe, Resend, Vitest and Playwright.",
      caption: "Stack. Post first for recruiters and CTOs.",
      width: 1080,
      height: 1350,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-layers.png",
      alt: "Infographic of the dependency layers, showing each layer depending only on the one beneath it.",
      caption: "Architecture layers. Shows the one-way dependency rule.",
      width: 1080,
      height: 1080,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-before-after.png",
      alt: "Infographic comparing four architecture metrics before and after the refactor sprints.",
      caption: "Before and after. The strongest proof for recruiters.",
      width: 1080,
      height: 1080,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-site-map.png",
      alt: "Infographic mapping the storefront, admin and docs areas of the site and their main routes.",
      caption: "Site map. Shows clients how much is included.",
      width: 1080,
      height: 1350,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-flow.png",
      alt: "Infographic of the journey from cart to payment to confirmation email.",
      caption: "Cart to confirmation email. Best for client posts.",
      width: 1080,
      height: 1350,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-gates.png",
      alt: "Infographic listing the seven quality gates every change must pass before merging.",
      caption: "Quality gates. Shows the engineering discipline behind the template.",
      width: 1080,
      height: 1080,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-offer.png",
      alt: "Infographic of what is included, what can be customised and how handover works.",
      caption: "The client offer. Post with a call to action.",
      width: 1080,
      height: 1350,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-table.png",
      alt: "Table of the five test layers, the tool each uses and what each one proves.",
      caption: "Testing table. Explains how every layer is tested.",
      width: 1080,
      height: 1350,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-bar-chart.png",
      alt: "Vertical story image with a bar chart of automated test counts by layer: unit, integration, smoke, accessibility and SEO.",
      caption: "Test counts. A 1080×1920 story for Instagram, Facebook and LinkedIn stories.",
      width: 1080,
      height: 1920,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-line-chart.png",
      alt: "Illustrative line chart: total cost from scratch climbs steeply over three years, while a tested template starts lower and rises gently.",
      caption: "Build versus template. Illustrative, for client posts.",
      width: 1080,
      height: 1080,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-sequence.png",
      alt: "Sequence diagram of the back-in-stock flow between the customer, the store, the database and Resend.",
      caption: "Back in stock, end to end. Shows a real flow across services.",
      width: 1080,
      height: 1350,
    },
    { type: "heading", text: "Recruiter pack" },
    {
      type: "paragraph",
      text: "Six slides for recruiters and hiring managers. Proof comes before technology, and the proof numbers are read from the latest test run. Post them in this order as one carousel or album.",
    },
    {
      type: "table",
      headers: ["Order", "Slide", "Job"],
      rows: [
        ["1", "/showcase/social/infographic-recruiter-built.png", "What was built and why it matters"],
        ["2", "/showcase/social/infographic-recruiter-proof.png", "Tests, coverage ratchet and merge gates"],
        ["3", "/showcase/social/infographic-recruiter-judgement.png", "The one-way dependency rule, enforced by CI"],
        ["4", "/showcase/social/infographic-sequence.png", "Back in stock as a worked example"],
        ["5", "/showcase/social/infographic-stack.png", "The technology, last"],
        ["6", "/showcase/social/recruiter-cta.png", "QR code and contact"],
      ],
    },
    {
      type: "image",
      src: "/showcase/social/infographic-recruiter-built.png",
      alt: "Table of what was built and why each part matters: storefront and checkout, admin, email platform, back-in-stock alerts and docs.",
      caption: "Recruiter 1. Outcomes first.",
      width: 1080,
      height: 1350,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-recruiter-proof.png",
      alt: "Table of measured proof: automated test count, line and branch coverage, deep imports and merge gates, with what keeps each honest.",
      caption: "Recruiter 2. Proof, read from the latest test run.",
      width: 1080,
      height: 1350,
    },
    {
      type: "image",
      src: "/showcase/social/infographic-recruiter-judgement.png",
      alt: "Layer diagram showing dependencies flow one way: app, features, feature internals, then shared lib.",
      caption: "Recruiter 3. One engineering judgement, enforced by CI.",
      width: 1080,
      height: 1350,
    },
    {
      type: "image",
      src: "/showcase/social/recruiter-cta.png",
      alt: "Closing slide asking 'Hiring for a build like this?' with a QR code to the case study and a contact email.",
      caption: "Recruiter 6. The close, with QR and contact.",
      width: 1080,
      height: 1350,
    },
    {
      type: "table",
      title: "Download kit per channel",
      headers: ["Channel", "Upload", "Why"],
      rows: [
        [
          "LinkedIn",
          "/showcase/social/linkedin-carousel.pdf as a document post",
          "Document posts swipe like a carousel and get the most dwell time.",
        ],
        [
          "Facebook",
          "/showcase/social/square-starters.png, /showcase/social/square-locks.png",
          "Squares crop cleanly in the feed and on mobile.",
        ],
        [
          "Telegram",
          "/showcase/social/carousel-cover.png, /showcase/social/carousel-products.png, /showcase/social/carousel-starters.png, /showcase/social/carousel-locks.png, /showcase/social/carousel-history.png, /showcase/social/carousel-flow.png, /showcase/social/carousel-layers.png, /showcase/social/carousel-cta.png as one album",
          "Albums show the slides in order, like the LinkedIn carousel.",
        ],
        [
          "X",
          "/showcase/social/square-layers.png",
          "One image per post. Use the video clip for the thread opener.",
        ],
      ],
    },
    { type: "heading", text: "Image and link pairings" },
    {
      type: "table",
      headers: ["Post theme", "Attach", "Link to"],
      rows: [
        ["Seasonal campaigns", "public/docs/showcase/email-black-friday.png and email-christmas.png", "[live URL]/docs/email-seasonal-campaigns"],
        ["Email builder overview", "public/docs/showcase/email-newsletter.png", "[live URL]/docs/case-study-email-platform"],
        ["Security and permissions", "Screenshot of the defence-in-depth diagram on the security page", "[live URL]/docs/security-and-compliance-posture"],
        ["Engineering process", "Screenshot of the test growth table on the engineering quality page", "[live URL]/docs/engineering-quality"],
        ["Changelog roundup", "The docs link preview card itself", "[live URL]/docs/whats-new"],
      ],
    },
    { type: "heading", text: "LinkedIn (professional, recruiters and CTOs)" },
    {
      type: "paragraph",
      text: "Post 1: I built a block-based email builder into a Next.js commerce platform, the kind of tool teams usually rent from Klaviyo or Mailchimp. Staff build emails from blocks, pull real products and prices from the catalog, and start from Black Friday, Bank Holiday or Christmas starters. Every save is versioned (last 50 kept, the original always kept), brand headers can be saved once and reused, and brand-critical blocks can be locked. Each feature shipped as a small PR with the tests written first. Case study: [live URL]/docs/case-study-email-platform",
    },
    {
      type: "paragraph",
      text: "Post 2: One permission check is a single point of failure. When I added block locking, I checked who can lock in three independent places: the request proxy, every server action, and the UI. Building it also exposed a real gap, email server actions that trusted the page to have checked the user, so every action now verifies the caller itself. The rules live in small pure functions with their own tests. Write-up with diagrams: [live URL]/docs/security-and-compliance-posture",
    },
    {
      type: "paragraph",
      text: "Post 3 (process): Across 140+ small reviewed PRs I shipped an email builder, a permissions model and a documentation library for five audiences: customers, content managers, developers, CTOs and the owner. Every sprint followed the same loop: failing test, smallest change to pass, type-check, squash-merge, docs updated in the same week. The full changelog is public: [live URL]/docs/whats-new",
    },
    { type: "heading", text: "Facebook business page (clients and store owners)" },
    {
      type: "paragraph",
      text: "Seasonal sales without the scramble. Our store platform now includes ready-made Black Friday, Bank Holiday and Christmas email starters. Pick one, swap in your offer, and the real products and prices come straight from your catalog. Your logo and footer stay locked so nothing gets changed by accident, and every edit can be undone. See the finished emails: [live URL]/docs/email-seasonal-campaigns",
    },
    {
      type: "paragraph",
      text: "Own your store and your email in one place. No separate email subscription, no copying products between tools, and every customer email (order confirmations, refunds, campaigns) lives alongside your orders. Interested in something like this for your business? Send us a message.",
    },
    { type: "heading", text: "Telegram (developer and founder channels)" },
    {
      type: "paragraph",
      text: "Short drop: Next.js 16 + Prisma/Neon + Better Auth commerce build, now with a block email builder (versioning, saved sections, seasonal starters, locked blocks) and defence-in-depth permissions (proxy + server actions + UI). Decision records and diagrams are all public: [live URL]/docs/architecture-decision-records",
    },
    { type: "heading", text: "X (short form)" },
    {
      type: "list",
      items: [
        "Shipped: Black Friday, Bank Holiday and Christmas email starters that pull live products from the catalog. [live URL]/docs/email-seasonal-campaigns",
        "Permissions checked in 3 places: proxy, server actions, UI. Rules are pure functions with tests. [live URL]/docs/security-and-compliance-posture",
        "Email hero images: 7.6 MB down to 1.25 MB with no visible quality loss. Small wins add up.",
      ],
    },
    { type: "heading", text: "Posting order" },
    {
      type: "steps",
      items: [
        { title: "Week 1", text: "LinkedIn Post 1 (case study) and the Facebook seasonal post. These lead with outcomes." },
        { title: "Week 2", text: "LinkedIn Post 2 (security) and the Telegram drop. These lead with engineering depth." },
        { title: "Week 3", text: "LinkedIn Post 3 (process and changelog) and the X thread. Reply to comments with links to specific docs pages." },
      ],
    },
    {
      type: "callout",
      variant: "warning",
      title: "Keep claims accurate",
      text: "Scheduled sends are built but not switched on, and the full browser test waits on a test admin account. Say 'built and tested' for scheduling, not 'live'. Accurate claims hold up when a CTO opens the repo.",
    },
  ],
}
