import type { Doc } from "../schema"

export const systemArchitecture: Doc = {
  slug: "system-architecture-overview",
  title: "System Architecture Overview",
  category: "Architecture",
  audience: "developer",
  access: "admin",
  summary:
    "The whole system on one page: the Next.js App Router front, the port/adapter data seam, Neon Postgres via Prisma, and the third-party edges (Resend, Stripe, and the planned Strapi CMS). Start here, then follow the links into auth and the data layer.",
  readingMinutes: 11,
  order: 1,
  updatedAt: "2026-09-26",
  tags: ["architecture", "next.js", "rsc", "prisma", "neon", "ports and adapters"],
  body: [
    {
      type: "paragraph",
      text: "MOMO is a server-first Next.js application. Pages are React Server Components by default; the browser only receives interactive islands (cart, admin forms, charts, mermaid diagrams). Every piece of business data lives in Neon Postgres and is reached through a thin port/adapter seam, so the UI never talks to the database — or, later, to Strapi — directly. This guide is the map; the auth and data-layer guides are the territory.",
    },
    {
      type: "heading",
      text: "The system at a glance",
    },
    {
      type: "mermaid",
      kind: "architecture",
      title: "Figure 1 — System context",
      caption:
        "Requests enter through the App Router. Server Components read through the data seam; the seam is the only thing that knows about Prisma, Neon, or the CMS.",
      diagram: [
        "flowchart TD",
        "  subgraph Client[Browser]",
        "    UI[RSC-rendered pages]",
        "    ISL[Client islands: cart, admin forms, charts]",
        "  end",
        "  subgraph Edge[Next.js App Router]",
        "    RSC[Server Components]",
        "    SA[Server Actions]",
        "    RH[Route handlers]",
        "  end",
        "  subgraph Seam[Data seam: features/* + lib/*]",
        "    PORT[Ports: typed domain APIs]",
        "    ADPT[Adapters: Prisma / seed / CMS]",
        "  end",
        "  subgraph Data[Persistence and services]",
        "    NEON[(Neon Postgres)]",
        "    RESEND[Resend email]",
        "    STRIPE[Stripe payments]",
        "    STRAPI[Strapi CMS - planned]",
        "  end",
        "  UI --> RSC",
        "  ISL --> SA",
        "  ISL --> RH",
        "  RSC --> PORT",
        "  SA --> PORT",
        "  PORT --> ADPT",
        "  ADPT --> NEON",
        "  ADPT -. future .-> STRAPI",
        "  SA --> RESEND",
        "  SA --> STRIPE",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "Layers and their one job",
    },
    {
      type: "table",
      headers: ["Layer", "Lives in", "Single responsibility"],
      rows: [
        ["Pages & layouts", "app/**", "Route, compose, and render. Server Components by default."],
        ["Client islands", "features/**/components", "Only the interactive bits: cart, admin forms, charts, mermaid."],
        ["Ports (domain API)", "features/*/api, lib/*/index", "Typed functions the UI calls. No SQL, no fetch shape leaks out."],
        ["Adapters", "lib/*/db-actions, *-source", "Translate a port call into Prisma, the code seed, or a CMS fetch."],
        ["Schema", "prisma/schema.prisma", "The single source of truth for the Neon tables."],
      ],
    },
    {
      type: "callout",
      variant: "tip",
      title: "The rule that keeps this clean",
      text: "A React component may import a port, never an adapter. If a page ever imports Prisma or a raw fetch, the seam has been breached — push that call down into an adapter and expose a typed port instead.",
    },
    {
      type: "heading",
      text: "How a page render flows",
    },
    {
      type: "mermaid",
      kind: "sequence",
      title: "Figure 2 — Server render of a data-backed page",
      caption: "The storefront and admin both follow this shape: RSC → port → adapter → Neon, with the seed as a fallback.",
      diagram: [
        "sequenceDiagram",
        "  participant B as Browser",
        "  participant P as Page (RSC)",
        "  participant PO as Port",
        "  participant AD as Adapter",
        "  participant DB as Neon",
        "  B->>P: GET /products",
        "  P->>PO: getCatalog()",
        "  PO->>AD: read merged catalog",
        "  AD->>DB: SELECT overlay rows",
        "  DB-->>AD: rows",
        "  AD-->>PO: seed merged with overlay",
        "  PO-->>P: typed Product[]",
        "  P-->>B: streamed HTML + minimal JS",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "Reads and writes are not symmetric",
    },
    {
      type: "paragraph",
      text: "Reads happen in Server Components during render — cheap, cached, and streamed. Writes happen through Server Actions invoked from client islands, and every write that touches business data is admin-guarded server-side and, where stock or money is involved, transactional. The catalog guide covers the merge-on-read model; the data-layer guide covers the transactional write path.",
    },
    {
      type: "steps",
      items: [
        { title: "Read (render time)", text: "Server Component calls a port; the adapter reads Neon (or the seed fallback) and returns typed domain objects. No client round-trip." },
        { title: "Write (user action)", text: "Client island calls a Server Action; the action re-checks the admin role, mutates Neon, and revalidates the affected cache tag." },
        { title: "Reconcile", text: "Providers update optimistically for snappy UI, then reconcile against the value the action returns, so the screen never drifts from the database." },
      ],
    },
    {
      type: "heading",
      text: "The technology, and why each is here",
    },
    {
      type: "table",
      headers: ["Concern", "Choice", "Why"],
      rows: [
        ["Framework", "Next.js App Router", "Server-first rendering, Server Actions, and ISR in one model."],
        ["Language", "TypeScript end to end", "The domain types are the contract between UI, ports, and adapters."],
        ["Database", "Neon Postgres", "Serverless Postgres with pooled + direct URLs for app vs. migrations."],
        ["ORM", "Prisma", "Typed schema as the single source of truth; transactions for stock/orders."],
        ["Auth", "Better Auth on Neon", "Server-verified sessions and password hashing; role via allowlist."],
        ["Email", "Resend", "Transactional and campaign sends from a verified domain."],
        ["Payments", "Stripe", "Server-validated checkout; totals recomputed server-side."],
        ["CMS (planned)", "Strapi", "Slot behind the same seam so content editing moves without a rewrite."],
      ],
    },
    {
      type: "callout",
      variant: "note",
      title: "Why the seam matters for Strapi",
      text: "The docs, catalog, and articles all read through the same port shape the CMS will one day satisfy. When Strapi lands, an adapter swaps from 'read the code seed' to 'read the CMS' and the pages never change. That is the entire migration strategy in one sentence.",
    },
    {
      type: "heading",
      text: "Where to go next",
    },
    {
      type: "list",
      items: [
        "Authentication & Authorization — how sessions, roles, and server-side guards enforce access.",
        "Data Layer & Database — the Neon schema, the port/adapter seam in detail, and the transactional write path.",
        "The Strapi Migration Runbook — the step-by-step for moving content behind the seam.",
      ],
    },
  ],
}
