import type { Doc } from "../lib/domain/schema"

export const theThemeSystem: Doc = {
  slug: "the-theme-system",
  title: "The Theme System",
  category: "Architecture",
  audience: "developer",
  access: "public",
  summary:
    "How brand identity became a single source of truth: a library of named theme templates in the StoreSettings.theme JSON column, one active at a time, resolved server-side and injected as CSS variables after globals.css so the storefront, admin, and email all re-theme with zero per-component edits and no flash on first paint.",
  readingMinutes: 10,
  order: 6,
  updatedAt: "2026-10-04",
  tags: ["theme", "branding", "css variables", "ssr", "prisma", "architecture"],
  body: [
    {
      type: "paragraph",
      text: "The theme system exists to kill a specific class of bug: brand colours drifting apart because they were hard-coded in a dozen places. Instead there is one library of theme templates, exactly one active, stored in the StoreSettings singleton and resolved on the server at render. Every surface — storefront, admin, email — reads the same resolved tokens, so nothing can fall out of sync. This guide is the technical companion to the admin-facing Managing Your Theme guide.",
    },
    {
      type: "heading",
      text: "The model",
    },
    {
      type: "paragraph",
      text: "A theme is not a single colour field — it's a library. StoreSettings.theme (a Json column on the settings singleton) holds a ThemeState: an array of ThemeTemplate plus the id of the active one. This is what lets a client keep a seasonal or campaign theme on the shelf and switch to it without losing their default.",
    },
    {
      type: "code",
      language: "typescript",
      title: "features/settings/lib/domain/theme.ts — the persisted shape",
      code: [
        "interface ThemeState {",
        "  activeThemeId: string",
        "  themes: ThemeTemplate[]",
        "}",
        "",
        "interface ThemeTemplate {",
        "  id: string",
        "  name: string",
        "  kind: 'system' | 'custom' | 'seasonal'",
        "  headingStyle: 'two-tone' | 'solid' | 'gradient'",
        "  headingAccent: { h1, h2, cards }  // per-tier accent reach (each on/off)",
        "  tokens: ThemeTokens & { light?: Partial<ThemeTokens>; dark?: Partial<ThemeTokens> }",
        "}",
        "",
        "interface ThemeTokens {",
        "  accent: string        // -> --accent-teal",
        "  accentMuted: string   // -> --accent-teal-muted",
        "  gradientFrom?: string // whole-title gradient start",
        "  gradientTo?: string   // whole-title gradient end",
        "}",
      ].join("\n"),
    },
    {
      type: "callout",
      variant: "tip",
      title: "Everything is pure and serialisable",
      text: "The whole module is pure functions over plain objects, so a ThemeState round-trips through the JSON column untouched. That's what makes the admin editing, the SSR resolve, and any future Strapi mapping trivial — there's no class instance or runtime state to reconstruct.",
    },
    {
      type: "heading",
      text: "How it reaches the page",
    },
    {
      type: "mermaid",
      kind: "architecture",
      title: "Figure 1 — One source, injected as variables",
      caption:
        "The active template is resolved on the server and emitted as an inline <style> after globals.css. Because it wins the cascade, every component that already reads --accent-teal re-themes for free — storefront, admin, and email alike.",
      diagram: [
        "flowchart TD",
        "  subgraph DB[Neon Postgres]",
        "    SS[(StoreSettings.theme JSON)]",
        "  end",
        "  subgraph Server[Next.js server render]",
        "    NORM[normalizeThemeState]",
        "    ACT[getActiveTheme]",
        "    CSS[buildThemeCss -> :root + .dark]",
        "  end",
        "  subgraph Client[Rendered document]",
        "    STYLE[inline style#brand-theme after globals.css]",
        "    VARS[--accent-teal / --accent-teal-muted / --brand-gradient-*]",
        "  end",
        "  SS --> NORM --> ACT --> CSS --> STYLE --> VARS",
        "  VARS --> SF[Storefront components]",
        "  VARS --> AD[Admin components]",
        "  VARS --> EM[Email accent]",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "The resolve pipeline",
    },
    {
      type: "steps",
      items: [
        { title: "normalizeThemeState(value)", text: "Coerces the unknown JSON value (or a missing column) into a valid ThemeState, falling back to DEFAULT_THEME_STATE. Nothing downstream ever sees a malformed theme." },
        { title: "getActiveTheme(state)", text: "Returns the live template — the active id, else the first template, else the built-in Titanium Teal. Always total." },
        { title: "resolveTokens(theme, scheme)", text: "Merges base tokens with the per-scheme (light/dark) override, and derives gradient endpoints from accents when not set explicitly." },
        { title: "buildThemeCss(theme)", text: "Emits `:root { … }` (light) and `.dark { … }` blocks overriding the accent/gradient variables. Rendered as an inline <style> after globals.css so it wins the cascade." },
      ],
    },
    {
      type: "callout",
      variant: "note",
      title: "Why inline <style>, SSR-seeded",
      text: "The overrides are emitted during the server render (BrandThemeStyle), so the correct palette is in the very first HTML payload. There is no client fetch and no flash of the default theme before the client's theme loads.",
    },
    {
      type: "heading",
      text: "The default is a visual no-op",
    },
    {
      type: "paragraph",
      text: "Titanium Teal's light/dark values are the exact tokens that already shipped in globals.css. Activating it changes nothing on screen — which is the point: introducing the single source of truth was safe by construction, and the store only ever looks different once someone deliberately edits or switches a theme.",
    },
    {
      type: "heading",
      text: "Heading style and the two-tone primitive",
    },
    {
      type: "paragraph",
      text: "headingStyle on the active template drives the shared TwoToneTitle primitive. In two-tone mode the accent falls on the last whitespace-delimited word (so multi-line titles split on the newline correctly); a title may also mark an explicit accent word. Solid renders one colour; gradient fades --brand-gradient-from to --brand-gradient-to.",
    },
    {
      type: "paragraph",
      text: "Style is one axis; reach is the other. Reach is per-tier: headingAccent is { h1, h2, cards } and each flag is injected as data-accent-h1 | data-accent-h2 | data-accent-cards on <html> alongside data-heading-style. SectionHeading derives a heading's tier automatically — emphasis 'secondary' is the 'card' tier, as='h1' is the 'h1' tier, everything else is 'h2' — and tags the markup with .tt-*--h1 | .tt-*--h2 | .tt-*--card. When a tier's attribute is 'off', CSS neutralises that tier's accent back to currentColor; the three switch independently, so a client can accent h1 but not h2 or cards — any combination. All of it is pure CSS driven by the data attributes — no component branches on the theme, so nothing re-renders and there's no per-page wiring. (The legacy headingScope field still migrates: 'all' maps to every tier on, otherwise the shipped default.)",
    },
    {
      type: "code",
      language: "tsx",
      code: [
        "// One entry point for every heading. Two-tone by default; the per-tier",
        "// accent reach follows the active theme via data-accent-* on <html>.",
        "<SectionHeading as=\"h1\" title=\"A decade of listening.\" />              // h1 tier",
        "<SectionHeading as=\"h2\" title=\"Built to last\" />                       // h2 tier",
        "<SectionHeading as=\"h3\" title={milestone.title} emphasis=\"secondary\" /> // card tier",
      ].join("\n"),
    },
    {
      type: "mermaid",
      kind: "state",
      title: "Figure 2 — headingStyle drives the primitive",
      caption: "A single field on the active template decides how every heading renders. No component branches on brand — they all defer to the primitive.",
      diagram: [
        "stateDiagram-v2",
        "  [*] --> two_tone",
        "  two_tone --> solid: headingStyle = solid",
        "  two_tone --> gradient: headingStyle = gradient",
        "  solid --> two_tone: headingStyle = two-tone",
        "  gradient --> two_tone: headingStyle = two-tone",
        "  solid --> gradient: headingStyle = gradient",
        "  gradient --> solid: headingStyle = solid",
      ].join("\n"),
    },
    {
      type: "mermaid",
      kind: "flow",
      title: "Figure 3 — per-tier toggles gate each heading",
      caption: "Style and reach are independent. A heading's tier (h1 / h2 / card) plus that tier's data-accent-* toggle decide whether the accent applies, entirely in CSS.",
      diagram: [
        "flowchart TD",
        "  H[Heading via SectionHeading] --> T{which tier?}",
        "  T -->|h1| A1{data-accent-h1?}",
        "  T -->|h2| A2{data-accent-h2?}",
        "  T -->|card| AC{data-accent-cards?}",
        "  A1 -->|on| ACC[Accent applies]",
        "  A2 -->|on| ACC",
        "  AC -->|on| ACC",
        "  A1 -->|off| PLAIN[Accent neutralised to currentColor]",
        "  A2 -->|off| PLAIN",
        "  AC -->|off| PLAIN",
      ].join("\n"),
    },
    {
      type: "heading",
      text: "Writing a theme",
    },
    {
      type: "paragraph",
      text: "The admin never mutates the JSON directly. It calls the pure transforms — upsertTheme, activateTheme, removeTheme, duplicateTheme — to produce a new ThemeState, then persists it through the settings Server Action, which re-checks the admin role and writes the column. Reads happen at render; the write path is the same admin-guarded, single-source pattern as the rest of the store.",
    },
    {
      type: "mermaid",
      kind: "sequence",
      title: "Figure 3 — Activating a theme",
      caption: "Admin islands transform state with pure helpers; the Server Action is the only thing that touches Neon.",
      diagram: [
        "sequenceDiagram",
        "  participant A as Admin island",
        "  participant H as Pure helpers",
        "  participant SA as updateStoreSettings action",
        "  participant DB as Neon",
        "  A->>H: activateTheme(state, id)",
        "  H-->>A: next ThemeState",
        "  A->>SA: save(next)",
        "  SA->>SA: re-check admin role",
        "  SA->>DB: write StoreSettings.theme",
        "  DB-->>SA: ok",
        "  SA-->>A: revalidate -> re-render with new tokens",
      ].join("\n"),
    },
    {
      type: "callout",
      variant: "tip",
      title: "Adding a token is a three-line change",
      text: "Add the field to ThemeTokens, map it in buildThemeCss, and consume the CSS variable in globals.css. Because every surface reads variables, nothing else needs editing — the new token themes the whole app the moment it's emitted.",
    },
    {
      type: "heading",
      text: "Where to go next",
    },
    {
      type: "list",
      items: [
        "Managing Your Theme (content guide) — the admin-facing walkthrough of the four Theme tabs.",
        "System Architecture Overview — where the theme seam sits in the wider port/adapter picture.",
        "Email Templates — how the resolved accent flows into transactional and campaign email.",
      ],
    },
  ],
}
