import type { Doc } from "../lib/domain/schema"

export const whatsNew: Doc = {
  slug: "whats-new",
  title: "What's New",
  category: "Technology Strategy",
  audience: "cto",
  access: "public",
  summary:
    "A dated changelog of everything shipped in the email builder, permissions and documentation programme, from the Product picks block (PR #70) to the owner permissions page (PR #92), the architecture and engineering-quality refactors through PR #187, and the showcase and launch-collateral run through PR #194. Each entry says what changed and why it matters.",
  readingMinutes: 7,
  order: 1,
  updatedAt: "2026-10-10",
  tags: ["changelog", "release notes", "email builder", "security", "documentation", "showcase"],
  body: [
    {
      type: "paragraph",
      text: "Each change shipped as a small reviewed pull request: tests written first, type-check clean and squash-merged into main. Entries are grouped by theme and listed oldest first within each group.",
    },
    { type: "heading", text: "Email builder" },
    {
      type: "table",
      headers: ["PR", "What shipped", "Why it matters"],
      rows: [
        ["#70", "Product picks block", "Emails show real catalog products with live prices and images instead of pasted copy."],
        ["#71", "One shared preview pane", "Template and campaign editors render exactly the same preview, so what you see is what is sent."],
        ["#72", "Undo/redo, copy hints and dark-mode-safe email shell", "Editing mistakes can be reversed, weak copy is flagged, and emails read well in dark-mode inboxes."],
        ["#73", "Reset button fix", "Reset to default now restores the editor immediately."],
        ["#74", "Discard, Duplicate and unsaved-changes guard", "No more lost work when closing the editor, and any template can be copied in one click."],
        ["#75", "Renderer, copy-quality and reset test coverage", "The email renderer is protected by automated tests before larger changes."],
        ["#76", "Version history, restore and Reset to original", "Every save is recorded; the last 50 can be restored and the original is always kept."],
        ["#77", "Placeholder picker and typo warnings", "Tokens like {{customer_name}} are inserted from a list, and unknown ones are flagged before sending."],
        ["#78", "Saved sections", "Brand headers and footers are saved once and inserted into any template as independent copies."],
        ["#79", "Starter gallery with seasonal campaigns", "New templates start from Newsletter, Product launch, Sale, Announcement, Black Friday, Bank Holiday or Christmas starters."],
        ["#80", "Hero images shrunk from 7.6 MB to 1.25 MB", "Faster emails and editor loads with no visible quality loss."],
        ["#81", "Locked blocks", "Brand-critical blocks cannot be edited, moved or deleted by accident."],
      ],
    },
    { type: "heading", text: "Security and permissions" },
    {
      type: "table",
      headers: ["PR", "What shipped", "Why it matters"],
      rows: [
        ["#83", "Lock permission for the owner and named admins", "Only trusted admins can lock or unlock blocks, checked in three independent places: proxy, server actions and UI."],
        ["#83", "Admin check on every email server action", "Closed a gap where email actions trusted the page to have checked the user. Each action now verifies the caller itself."],
        ["#83", "Request proxy for admin routes", "Signed-out visitors are redirected before any admin page code runs."],
        ["#91", "Lock permissions stored in the database, with an audit log", "Who can lock changes instantly without a redeploy, and every grant or revoke is recorded."],
        ["#92", "Permissions page in Admin → Settings", "The owner grants or revokes lock rights with one switch per admin; other admins see a read-only view."],
      ],
    },
    { type: "heading", text: "Documentation" },
    {
      type: "table",
      headers: ["PR", "What shipped", "Audience"],
      rows: [
        ["#82", "Developer and in-app docs caught up for PRs #63 to #81", "Developers, content managers"],
        ["#84", "Security posture rewrite, permissions matrix and email architecture diagrams", "CTOs, security reviewers, developers"],
        ["#85", "Engineering quality, decision records and contributing workflow", "CTOs, recruiters, contributors"],
        ["#86", "Seasonal campaign walkthrough with real screenshots, and a platform glossary", "Content managers, clients, everyone"],
      ],
    },
    { type: "heading", text: "Architecture and engineering quality" },
    {
      type: "paragraph",
      text: "A run of behaviour-preserving refactor sprints moved the codebase to a strict feature-sliced layout. Every slice now has one public entry and a lib folder with exactly four roles: actions, data, domain and adapters. Each step was guarded by a ratchet so it cannot slide back.",
    },
    {
      type: "table",
      headers: ["PR", "What shipped", "Why it matters"],
      rows: [
        ["#101", "Shared fake-data test kit (qa/fakes)", "Tests build on one set of fakes instead of copy-pasting setup, so new tests are cheaper to write."],
        ["#103", "Slice boundaries: 0 deep imports, 0 lib-to-features inversions, plus a lint rule", "Features can only be reached through their public entry, so a slice can be changed or replaced without ripple effects."],
        ["#106", "Auth split into actions, data, domain and adapters", "The most security-sensitive code now follows the same predictable shape as every other slice."],
        ["#114", "Four-folder lib split across 11 slices, finished in #115 to #119", "Anyone can find where a rule, a query or an outside call lives without searching."],
        ["#121", "Hardened guards for inversions and prop drilling", "The architecture scorecard fails the build if the layering regresses."],
        ["#122", "Public server actions guarded; server-only exports moved out of use-server endpoints", "Admin mutations cannot be called by an unauthorised visitor, and secrets-adjacent helpers are no longer exposed as endpoints."],
        ["#124", "Auth and checkout origin resolution stabilised", "Sign-in and Stripe return URLs always land on the canonical site, including behind a proxy."],
        ["#146", "Checkout hydration and local-image origin fixes", "Checkout renders without hydration warnings and product images load from the correct origin."],
        ["#187", "Every page points its canonical at itself and carries its own card titles", "Documentation pages rank for their own content instead of being folded into the home page, and a link shared on X previews with that page's title rather than the store name."],
      ],
    },
    { type: "heading", text: "Stock alerts, checkout and showcase" },
    {
      type: "table",
      headers: ["PR", "What shipped", "Why it matters"],
      rows: [
        ["#154", "Back-in-stock requests with a Notify me form", "Sold-out products keep collecting interest instead of losing the shopper."],
        ["#155", "Restocking sends the back-in-stock email once, with unsubscribe", "Everyone waiting hears the moment stock returns, without anyone sending it by hand."],
        ["#156", "Waiting column and Most wanted card in admin", "You can see demand before you reorder."],
        ["#157", "Generated facts and a coverage ratchet", "Numbers on slides come from the repo, and test coverage can only go up."],
        ["#163", "Seeded demo admin and audience video cuts", "Recruiter, buyer and engineer videos are recorded from real screens."],
        ["#166", "Checkout is sign-in only", "You sign in to check out, so every order is tied to an account and its order history."],
        ["#168", "Audience packs and a checkout sequence as LinkedIn carousel PDFs", "Each pack is one swipeable post instead of loose images."],
        ["#169", "Security, how-it-was-built and site-tour carousels", "Three more ready-to-post stories built from the same facts."],
      ],
    },
    { type: "heading", text: "Showcase, launch collateral and release discipline" },
    {
      type: "paragraph",
      text: "The run from S38 to S49 turned the launch collateral into something generated rather than assembled by hand: the numbers on every slide are read from a committed snapshot of the repo, the demo recordings are produced from real screens with every real person replaced by a stand-in, and the site map is derived from the app's own navigation. S46's canonical-URL work is listed under Architecture and engineering quality above.",
    },
    {
      type: "table",
      headers: ["PR", "What shipped", "Why it matters"],
      rows: [
        ["#172", "Launch kit renders the same on any machine: Geist Mono loaded locally, every asset re-rendered from real facts, one dev port", "Slides and carousels come out identical wherever they are generated, instead of depending on which fonts a machine happens to have."],
        ["#174", "A public showcase-launch-assets guide; the nine Positioning docs stay owner-only, now guarded by a test", "Anyone evaluating the template can see exactly what collateral it produces, while the sales material stays private by test rather than by care."],
        ["#175", "Posts and slides quote measured numbers from a committed fact snapshot", "Every figure in a post can be traced back to the commit that produced it, so nothing is quoted from memory."],
        ["#177", "Recordings pace by distance rather than step count, plus site-tour and enquiry-form clips", "Demo videos read at a human pace, and the enquiry clip stops before it would actually send."],
        ["#179", "Every real person in a recording is a stand-in, including the store's own contact details; clips refuse to film a broken or gated page", "No real contact details appear in a demo, and a recording fails loudly instead of quietly filming an error page."],
        ["#181", "Showcase assets grouped one folder per audience or topic, with the layout defined in one place and pinned by tests", "Collateral is where you expect it, and a contrast failure found while grouping it was fixed at the token for every page."],
        ["#183", "Slides and carousels re-exported from a fresh fact run", "Published assets quote current test and coverage figures instead of counts three sprints old."],
        ["#185", "A recruitment-first posting calendar as data: four weeks, sixteen slots, every asset scheduled exactly once", "Nothing generated is left unposted and nothing is posted twice, and a slot cannot link a file that is missing or owner-only."],
        ["#189", "Every carousel slide wears the AduDev brand, with two guards on the source and the rendered pixels", "The decks read as one company's work, and a store accent colour reaching a slide fails the build."],
        ["#191", "The site map is derived from the app's own navigation: four structure slides replace one hand-written one", "The map shown to a buyer or a candidate cannot drift from the real site, because a nav item that reaches no slide fails a test."],
        ["#194", "pnpm clean and pnpm health, plus a close-out step in the sprint workflow", "Regenerable build and test output is cleared every sprint instead of when someone notices, which is what made the browser suite flaky."],
        ["#196", "This page is checked against the sprint ledger, and eleven missing sprints were added", "The changelog cannot fall behind again: a merged sprint with no entry here fails a test, so what you are reading is the whole record rather than whatever was remembered."],
      ],
    },
    {
      type: "callout",
      variant: "info",
      title: "Still on the roadmap",
      text: "Scheduled campaign sends are built and tested but not switched on, and the full click-through browser test is waiting for a dedicated test admin account. Both are tracked rather than hidden.",
    },
  ],
}
