export { AdminGuard } from "./components/admin-guard"
export { AdminShell } from "./components/admin-shell"
export { DashboardOverview } from "./components/dashboard-overview"
export { ProductManager } from "./components/product-manager"
export { OrderManager } from "./components/order-manager"
export { CustomerManager } from "./components/customer-manager"
export { CustomerDetail } from "./components/customer-detail"
export { AnalyticsPanel } from "./components/analytics-panel"
export { OfferAnalyticsPanel } from "./components/offer-analytics-panel"
export { EmailManager } from "./components/email-manager"
export { AdminSettings } from "./components/admin-settings"
export { CompanyProfileView } from "./components/company-profile"
export { AdminOnboarding } from "./components/admin-onboarding"
export { adminNav, isActive } from "./lib/nav"
export type { AdminNavItem } from "./lib/nav"
