export { AdminGuard } from "./components/admin-guard"
export { AdminShell } from "./components/admin-shell"
export { DashboardOverview } from "./components/dashboard-overview"
export { ProductManager } from "./components/product-manager"
export { OrderManager } from "./components/order-manager"
export { AnalyticsPanel } from "./components/analytics-panel"
export { EmailManager } from "./components/email-manager"
export { adminNav, isActive } from "./lib/nav"
export type { AdminNavItem } from "./lib/nav"
